### ISSUE TITLE
Can't Stop Playing

### ISSUE THREAD

**Issue by devobenavidez** [mcwebb/angular-sound#2]
**regards**

I want to know how I can stop playing the audio, I tried to do 
**SoundService.getSound ('sound1').stop();**
but it returns Error

**InvalidStateError : An Attempt was made ​​to use an object That is not, or is no longer , usable.**

not if it's a mistake or not as making the arrest need to do it from the controller , I appreciate your help.

i set the **SoundService.getSound('sound1').start();** when i get a message inside son function and i try to stop when i cliked some button in another function.

**Comment by mcwebb** [comment]
Hi @dontripi,
I'm sorry for my late reply, I didn't see this.
`SoundService.getSound()` returns a new instance of `AudioBufferSourceNode` each time, thus `SoundService.getSound ('sound1').stop();` won't work because you're trying to stop a different instance of the sound which hasn't even been started. Instead you'll need to cache the instance locally e.g.:
```js
const sound1 = SoundService.getSound('sound1');
sound1.start();
setTimeout(() => sound1.stop(), 1000);
```
